// <auto-generated 
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TournamentApi.Data;

#nullable disable

namespace TournamentApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // --- Bracket ---
            modelBuilder.Entity("TournamentApi.Domain.Bracket", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("TournamentId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TournamentId")
                    .IsUnique();

                b.ToTable("Brackets");

                b.HasOne("TournamentApi.Domain.Tournament", "Tournament")
                    .WithOne("Bracket")
                    .HasForeignKey("TournamentApi.Domain.Bracket", "TournamentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Tournament");
                b.Navigation("Matches");
            });

            // --- Match ---
            modelBuilder.Entity("TournamentApi.Domain.Match", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("BracketId").HasColumnType("INTEGER");
                b.Property<int>("Player1Id").HasColumnType("INTEGER");
                b.Property<int>("Player2Id").HasColumnType("INTEGER");
                b.Property<int>("Round").HasColumnType("INTEGER");
                b.Property<int?>("WinnerId").HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("BracketId");
                b.HasIndex("Player1Id");
                b.HasIndex("Player2Id");
                b.HasIndex("WinnerId");

                b.ToTable("Matches");

                b.HasOne("TournamentApi.Domain.Bracket", "Bracket")
                    .WithMany("Matches")
                    .HasForeignKey("BracketId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TournamentApi.Domain.User", "Player1")
                    .WithMany("MatchesAsPlayer1")
                    .HasForeignKey("Player1Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("TournamentApi.Domain.User", "Player2")
                    .WithMany("MatchesAsPlayer2")
                    .HasForeignKey("Player2Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("TournamentApi.Domain.User", "Winner")
                    .WithMany("MatchesAsWinner")
                    .HasForeignKey("WinnerId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Bracket");
                b.Navigation("Player1");
                b.Navigation("Player2");
                b.Navigation("Winner");
            });

            // --- Tournament ---
            modelBuilder.Entity("TournamentApi.Domain.Tournament", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("StartDate").HasColumnType("TEXT");
                b.Property<int>("Status").HasColumnType("INTEGER");

                b.HasKey("Id");
                b.ToTable("Tournaments");

                b.Navigation("Bracket");
            });

            // --- User ---
            modelBuilder.Entity("TournamentApi.Domain.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                b.Property<string>("FirstName").IsRequired().HasColumnType("TEXT");
                b.Property<string>("LastName").IsRequired().HasColumnType("TEXT");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");

                b.Navigation("MatchesAsPlayer1");
                b.Navigation("MatchesAsPlayer2");
                b.Navigation("MatchesAsWinner");
            });

            
            modelBuilder.Entity("TournamentParticipants", b =>
            {
                b.Property<int>("TournamentId").HasColumnType("INTEGER");
                b.Property<int>("UserId").HasColumnType("INTEGER");

                b.HasKey("TournamentId", "UserId");
                b.HasIndex("UserId");

                b.ToTable("TournamentParticipants");

                b.HasOne("TournamentApi.Domain.Tournament", null)
                    .WithMany()
                    .HasForeignKey("TournamentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TournamentApi.Domain.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
